version: '3'

services:
  app:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    container_name: desafio3-app
    entrypoint: python3 src/console.py
    volumes:
      - .:/home/app/
    tty: true
    stdin_open: true
