name: Test pipeline
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d

      - name: Mypy - Check static typing
        run: docker-compose exec -T app pipenv run mypy src/**/*.py

      - name: Run coverage
        run: docker-compose exec -T app pipenv run coverage

      - name: Run coverage report
        run: docker-compose exec -T app pipenv run coverageReport

      - name: Run lint
        run: docker-compose exec -T app pipenv run flake8
