name: Test pipeline
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d

      - name: Pyright - Check static typing
        run: docker-compose exec -T app pipenv run pyright

      - name: Run tests
        run: docker-compose exec -T app pipenv run test

      - name: Run coverage
        run: docker-compose exec -T app pipenv run coverage

      # - name: Run coverage report
      #   run: docker-compose exec -T app pipenv run coverageReport

      - name: Run lint
        run: docker-compose exec -T app pipenv run flake8
